# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: apt-get update
- script: apt-get install build-essential libssl-dev
- script: curl https://raw.githubusercontent.com/creationix/nvm/0.25.0/install.sh | bash
- script: source ~/.profile
- script: nvm --version
- script: nvm install 6.15.1
- script: nvm use 6
- script: node -v
- script: npm install
- script: ls ./node_modules/.bin | grep wdio
- script: ./node_modules/.bin/wdio -v
- script: npx wdio -v
- script: npm rebuild node-fibers
- script: npm run single
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
